function hfig = initViewer(hfig, isBlankFlag)
if isempty(hfig)
    hfig = figure('WindowStyle', 'normal', ...
        'Tag', 'BioinfoMolviewer',...
        'toolbar', 'none',...
        'units', 'pixels',...
        'DeleteFcn', @onViewerClosing,...
        'resize', 'on',...
        'ResizeFcn', @resizeViewer,...
        'PaperPositionMode', 'auto', ...
        'Name', 'Molecule Viewer: Blank',...
        'numbertitle','off', ...
        'visible', 'on');
    initFigureTools(hfig, isBlankFlag)
end

appdata = createViewer(hfig);

if isBlankFlag
    appdata.noinputarg = true;
end
lSetAppData(hfig, appdata);

end